# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('entryType', models.CharField(choices=[('E', 'Event'), ('C', 'Class')], default='C', max_length=1)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('passed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile_of_entry', to='mainpage.Profile')),
            ],
        ),
    ]
