# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_auto_20161201_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='Registrations_of_user', to='mainpage.Registration'),
        ),
    ]
