# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_auto_20161212_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/nopic.png', null=True, upload_to=mainpage.models.get_user_path),
        ),
    ]
