# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_auto_20161212_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_create', 'Can create new events and classes'),)},
        ),
    ]
