# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_auto_20161230_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, help_text='Please enter age. [optional]', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Please enter your resting heart rate. [optional]', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, help_text='Please enter height in cm. [optional]', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Add your profile picture [optional]', null=True, upload_to=mainpage.models.get_user_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('REG', 'Regular'), ('TRN', 'Trainer'), ('ADM', 'Admin')], default='REG', help_text='Choose your user type. Regular users cannot create entries [THIS FIELD IS VISIBLE FOR TESTING PURPOSES]', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Please enter weight in kg. [optional]', null=True),
        ),
    ]
